steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cvtool/image-hash-api:$REVISION_ID', '-t', 'gcr.io/$PROJECT_ID/cvtool/image-hash-api:latest', '.']
  dir: ''
  waitFor: ['-']

images:
- 'gcr.io/$PROJECT_ID/cvtool/image-hash-api:latest'
- 'gcr.io/$PROJECT_ID/cvtool/image-hash-api:$REVISION_ID'
