# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ImageMatchResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, method=None, error=None, status=None):
        """
        ImageMatchResponse - a model defined in Swagger

        :param method: The method of this ImageMatchResponse.
        :type method: str
        :param error: The error of this ImageMatchResponse.
        :type error: str
        :param status: The status of this ImageMatchResponse.
        :type status: str
        """
        self.swagger_types = {
            'method': str,
            'error': str,
            'status': str
        }

        self.attribute_map = {
            'method': 'method',
            'error': 'error',
            'status': 'status'
        }

        self._method = method
        self._error = error
        self._status = status

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageMatchResponse of this ImageMatchResponse.
        :rtype: ImageMatchResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def method(self):
        """
        Gets the method of this ImageMatchResponse.

        :return: The method of this ImageMatchResponse.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """
        Sets the method of this ImageMatchResponse.

        :param method: The method of this ImageMatchResponse.
        :type method: str
        """

        self._method = method

    @property
    def error(self):
        """
        Gets the error of this ImageMatchResponse.

        :return: The error of this ImageMatchResponse.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """
        Sets the error of this ImageMatchResponse.

        :param error: The error of this ImageMatchResponse.
        :type error: str
        """

        self._error = error

    @property
    def status(self):
        """
        Gets the status of this ImageMatchResponse.

        :return: The status of this ImageMatchResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this ImageMatchResponse.

        :param status: The status of this ImageMatchResponse.
        :type status: str
        """

        self._status = status

